In [291]:
import numpy as np
import pandas as pd

In [292]:
my_data = ["Emincan" , "Alper" , "Burak" , "Dilara" , "Zeynep"]
my_data

['Emincan', 'Alper', 'Burak', 'Dilara', 'Zeynep']

In [293]:
pd.Series(my_data)

0    Emincan
1      Alper
2      Burak
3     Dilara
4     Zeynep
dtype: object

In [294]:
years = [1923 , 1776 , 1876]
countries = ["Turkey" , "USA" , "Canada"]

In [295]:
pd.Series(data = years , index = countries , dtype=float)

Turkey    1923.0
USA       1776.0
Canada    1876.0
dtype: float64

In [296]:
my_dict = {
    'Mehmet Ali' : 26,
    'Mustafa' : 23,
    'Osman' : 21,
    'Ahmet' : 29
} 
my_dict

{'Mehmet Ali': 26, 'Mustafa': 23, 'Osman': 21, 'Ahmet': 29}

In [297]:
pd.Series(my_dict)

Mehmet Ali    26
Mustafa       23
Osman         21
Ahmet         29
dtype: int64

In [298]:
q1 = {'Japan': 80 , 'China' : 450 , 'Turkey' : 150 , 'India' : 200}
q2 = {'Japan': 90 , 'China' : 420 , 'Turkey' : 230 , 'India' : 195 , 'Sivas' : 100}

In [299]:
sales_q1 = pd.Series(data = q1)
sales_q2 = pd.Series(data = q2)

In [300]:
sales_q1.index

Index(['Japan', 'China', 'Turkey', 'India'], dtype='object')

In [301]:
sales_q1

Japan      80
China     450
Turkey    150
India     200
dtype: int64

In [302]:
sales_total = sales_q2 + sales_q1
sales_total

China     870.0
India     395.0
Japan     170.0
Sivas       NaN
Turkey    380.0
dtype: float64

In [303]:
sales_total.keys()

Index(['China', 'India', 'Japan', 'Sivas', 'Turkey'], dtype='object')

In [304]:
resultSales = sales_q1.add(sales_q2 , fill_value = 0)
resultSales

China     870.0
India     395.0
Japan     170.0
Sivas     100.0
Turkey    380.0
dtype: float64

In [305]:
from numpy import random as rd

In [306]:
my_data = rd.randint(0,101 , size = (5,4))
my_data

array([[15, 53, 31, 40],
       [64, 33, 86, 41],
       [27, 69, 80, 91],
       [30, 70, 28, 75],
       [10, 98, 12, 13]], dtype=int32)

In [307]:
pd.DataFrame(my_data)

    0   1   2   3
0  15  53  31  40
1  64  33  86  41
2  27  69  80  91
3  30  70  28  75
4  10  98  12  13

In [308]:
my_idx = ["TR" , "BRA" , "USA" , "RU"]
my_cols = ["Jan" , "Feb" , "March"]
my_data = rd.randint(0,101 , size = (4,3))
df = pd.DataFrame(index = my_idx , data = my_data , columns=my_cols)
df

     Jan  Feb  March
TR    94    8     68
BRA   27   76     23
USA   91   26      5
RU    41   51     57

In [309]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, TR to RU
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   March   4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [310]:
df.describe()

             Jan        Feb      March
count   4.000000   4.000000   4.000000
mean   63.250000  40.250000  38.250000
std    34.277057  29.646529  29.295904
min    27.000000   8.000000   5.000000
25%    37.500000  21.500000  18.500000
50%    66.000000  38.500000  40.000000
75%    91.750000  57.250000  59.750000
max    94.000000  76.000000  68.000000

In [311]:
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [312]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [313]:
df.shape

(244, 11)

In [314]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [315]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [316]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [317]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id'],
      dtype='object')

In [318]:
df[['price_per_person']]

     price_per_person
0                8.49
1                3.45
2                7.00
3               11.84
4                6.15
..                ...
239              9.68
240             13.59
241             11.34
242              8.91
243              9.39

[244 rows x 1 columns]

In [319]:
print(type(df['price_per_person']))    # <class 'pandas.core.series.Series'>
print(type(df[['price_per_person']]))  # <class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [320]:
df[['sex','tip']]

        sex   tip
0    Female  1.01
1      Male  1.66
2      Male  3.50
3      Male  3.31
4    Female  3.61
..      ...   ...
239    Male  5.92
240  Female  2.00
241    Male  2.00
242    Male  1.75
243  Female  3.00

[244 rows x 2 columns]

In [321]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id'],
      dtype='object')

In [322]:
# İnsanların bonkörlük seviyelerini hespalayalım
df['Generousity'] = (df['tip']/df['total_bill']) *100
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,payment_id,Generousity
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.974441

In [323]:
df.columns = df.columns.str.lower()
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id',
       'generousity'],
      dtype='object')

In [324]:
df.drop(columns=['payment_id'] , axis=1 , inplace=True)
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'generousity'],
      dtype='object')

In [325]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,generousity
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,14.680765

In [326]:
df.set_index(keys='payer_name' , drop=True , inplace=True)

In [327]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.054159
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765

In [328]:
df.iloc[[10]]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
William Riley,10.27,1.71,Male,No,Sun,Dinner,2,5.14,566287581219,16.650438

In [329]:
df.loc[['Nathaniel Harris']]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041

In [330]:
df.iloc[2:6]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [331]:
df.loc['Travis Walters' : 'Erik Smith'] # Stop noktası dahil

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [332]:
df.drop('Travis Walters' , axis = 0 , inplace = True)

In [333]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [334]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [ ]:
df = df.reset_index() 
df.set_index('cc_number' , drop = True , append = False , inplace = False)
df.head(5)

,payer_name,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
cc_number,,,,,,,,,,
3560325168603410,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
4478071379779230,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
4676137647685994,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
4832732618637221,Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765
213140353657882,Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.623962