In [132]:
import numpy as np
import pandas as pd

In [133]:
my_data = ["Emincan" , "Alper" , "Burak" , "Dilara" , "Zeynep"]
my_data

['Emincan', 'Alper', 'Burak', 'Dilara', 'Zeynep']

In [134]:
pd.Series(my_data)

0    Emincan
1      Alper
2      Burak
3     Dilara
4     Zeynep
dtype: object

In [135]:
years = [1923 , 1776 , 1876]
countries = ["Turkey" , "USA" , "Canada"]

In [136]:
pd.Series(data = years , index = countries , dtype=float)

Turkey    1923.0
USA       1776.0
Canada    1876.0
dtype: float64

In [137]:
my_dict = {
    'Mehmet Ali' : 26,
    'Mustafa' : 23,
    'Osman' : 21,
    'Ahmet' : 29
} 
my_dict

{'Mehmet Ali': 26, 'Mustafa': 23, 'Osman': 21, 'Ahmet': 29}

In [138]:
pd.Series(my_dict)

Mehmet Ali    26
Mustafa       23
Osman         21
Ahmet         29
dtype: int64

In [139]:
q1 = {'Japan': 80 , 'China' : 450 , 'Turkey' : 150 , 'India' : 200}
q2 = {'Japan': 90 , 'China' : 420 , 'Turkey' : 230 , 'India' : 195 , 'Sivas' : 100}

In [140]:
sales_q1 = pd.Series(data = q1)
sales_q2 = pd.Series(data = q2)

In [141]:
sales_q1.index

Index(['Japan', 'China', 'Turkey', 'India'], dtype='object')

In [142]:
sales_q1

Japan      80
China     450
Turkey    150
India     200
dtype: int64

In [143]:
sales_total = sales_q2 + sales_q1
sales_total

China     870.0
India     395.0
Japan     170.0
Sivas       NaN
Turkey    380.0
dtype: float64

In [144]:
sales_total.keys()

Index(['China', 'India', 'Japan', 'Sivas', 'Turkey'], dtype='object')

In [145]:
resultSales = sales_q1.add(sales_q2 , fill_value = 0)
resultSales

China     870.0
India     395.0
Japan     170.0
Sivas     100.0
Turkey    380.0
dtype: float64

In [146]:
from numpy import random as rd

In [147]:
my_data = rd.randint(0,101 , size = (5,4))
my_data

array([[15, 20,  6, 45],
       [24, 27, 53, 24],
       [ 6, 63, 53, 32],
       [26, 74, 38,  0],
       [60, 25, 98, 38]], dtype=int32)

In [148]:
pd.DataFrame(my_data)

    0   1   2   3
0  15  20   6  45
1  24  27  53  24
2   6  63  53  32
3  26  74  38   0
4  60  25  98  38

In [149]:
my_idx = ["TR" , "BRA" , "USA" , "RU"]
my_cols = ["Jan" , "Feb" , "March"]
my_data = rd.randint(0,101 , size = (4,3))
df = pd.DataFrame(index = my_idx , data = my_data , columns=my_cols)
df

     Jan  Feb  March
TR    38   78     64
BRA   98   46     40
USA   27    7     74
RU    42   35     83

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, TR to RU
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   March   4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [151]:
df.describe()

             Jan        Feb      March
count   4.000000   4.000000   4.000000
mean   51.250000  41.500000  65.250000
std    31.805398  29.354159  18.536001
min    27.000000   7.000000  40.000000
25%    35.250000  28.000000  58.000000
50%    40.000000  40.500000  69.000000
75%    56.000000  54.000000  76.250000
max    98.000000  78.000000  83.000000

In [152]:
df = pd.read_csv("tips.csv")
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [153]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [154]:
df.shape

(244, 11)

In [155]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [156]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [158]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id'],
      dtype='object')

In [159]:
df[['price_per_person']]

     price_per_person
0                8.49
1                3.45
2                7.00
3               11.84
4                6.15
..                ...
239              9.68
240             13.59
241             11.34
242              8.91
243              9.39

[244 rows x 1 columns]

In [160]:
print(type(df['price_per_person']))    # <class 'pandas.core.series.Series'>
print(type(df[['price_per_person']]))  # <class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [161]:
df[['sex','tip']]

        sex   tip
0    Female  1.01
1      Male  1.66
2      Male  3.50
3      Male  3.31
4    Female  3.61
..      ...   ...
239    Male  5.92
240  Female  2.00
241    Male  2.00
242    Male  1.75
243  Female  3.00

[244 rows x 2 columns]

In [162]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id'],
      dtype='object')

In [163]:
# İnsanların bonkörlük seviyelerini hespalayalım
df['Generousity'] = (df['tip']/df['total_bill']) *100
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,payment_id,Generousity
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.974441

In [164]:
df.columns = df.columns.str.lower()
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id',
       'generousity'],
      dtype='object')

In [165]:
df.drop(columns=['payment_id'] , axis=1 , inplace=True)
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'generousity'],
      dtype='object')

In [166]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,generousity
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,14.680765

In [167]:
df.set_index(keys='payer_name' , drop=True , inplace=True)

In [168]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.054159
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765

In [169]:
df.iloc[[10]]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
William Riley,10.27,1.71,Male,No,Sun,Dinner,2,5.14,566287581219,16.650438

In [170]:
df.loc[['Nathaniel Harris']]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041

In [171]:
df.iloc[2:6]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [172]:
df.loc['Travis Walters' : 'Erik Smith'] # Stop noktası dahil

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,16.658734
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [173]:
df.drop('Travis Walters' , axis = 0 , inplace = True)

In [174]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [175]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,cc_number,generousity
payer_name,,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,213140353657882,18.623962

In [176]:
df = df.reset_index() 
df.set_index('cc_number' , drop = True , append = False , inplace = True)
df.head(5)

,payer_name,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
cc_number,,,,,,,,,,
3560325168603410,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
4478071379779230,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
4676137647685994,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
4832732618637221,Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765
213140353657882,Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.623962

In [177]:
df.head()

,payer_name,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
cc_number,,,,,,,,,,
3560325168603410,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
4478071379779230,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
4676137647685994,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
4832732618637221,Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765
213140353657882,Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.623962

In [178]:
df.columns.to_list()

['payer_name',
 'total_bill',
 'tip',
 'sex',
 'smoker',
 'day',
 'time',
 'size',
 'price_per_person',
 'generousity']

In [179]:
df.head()

,payer_name,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
cc_number,,,,,,,,,,
3560325168603410,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
4478071379779230,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
4676137647685994,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
4832732618637221,Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765
213140353657882,Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.623962

In [180]:
df.loc[3560325168603410:4832732618637221]

,payer_name,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
cc_number,,,,,,,,,,
3560325168603410,Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
4478071379779230,Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
4676137647685994,Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
4832732618637221,Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765

In [181]:
df.reset_index()
df.set_index(keys='payer_name' , drop=True ,inplace=True)

In [182]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
payer_name,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.623962

In [183]:
df.loc['Christy Cunningham':'Erik Smith']

,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
payer_name,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.623962

In [184]:
df.iloc[10:15]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
payer_name,,,,,,,,,
Diane Macias,35.26,5.00,Female,No,Sun,Dinner,4,8.82,14.180374
Chad Harrington,15.42,1.57,Male,No,Sun,Dinner,2,7.71,10.181582
Joshua Jones,18.43,3.00,Male,No,Sun,Dinner,4,4.61,16.277808
Vanessa Jones,14.83,3.02,Female,No,Sun,Dinner,2,7.42,20.364127
Matthew Reilly,21.58,3.92,Male,No,Sun,Dinner,2,10.79,18.164968

In [185]:
df2 = pd.DataFrame({'Year' : [1776,1867,1821] , 'Pop' : [328,38,126] , 'GDP' : [20.5,1.7,1.22]} , index =['USA','CANADA','MEXICO']) 
df2

        Year  Pop    GDP
USA     1776  328  20.50
CANADA  1867   38   1.70
MEXICO  1821  126   1.22

In [186]:
df2['Pop']>50

USA        True
CANADA    False
MEXICO     True
Name: Pop, dtype: bool

In [187]:
df2[df2['Pop'] > 50]

        Year  Pop    GDP
USA     1776  328  20.50
MEXICO  1821  126   1.22

In [188]:
df[df['total_bill']>40]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
payer_name,,,,,,,,,
Brian Ortiz,48.27,6.73,Male,No,Sat,Dinner,4,12.07,13.942407
Aaron Bentley,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,11.774956
Heather Cohen,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,5.643341
Eric Andrews,41.19,5.00,Male,No,Thur,Lunch,5,8.24,12.138869
Ryan Gonzales,48.17,5.00,Male,No,Sun,Dinner,6,8.03,10.379905
Gregory Clark,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,19.681165
Jose Parsons,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,7.717751
Stephen Cox,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,7.398274
Brooke Soto,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,11.598237
Alex Williamson,48.33,9.00,Male,No,Sat,Dinner,4,12.08,18.621974

In [189]:
df[(df['sex'] == 'Male') & (df['tip'] > 5)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
payer_name,,,,,,,,,
Lance Peterson,39.42,7.58,Male,No,Sat,Dinner,4,9.86,19.228818
Todd Cooper,30.40,5.60,Male,No,Sun,Dinner,4,7.60,18.421053
James Barnes,32.40,6.00,Male,No,Sun,Dinner,4,8.10,18.518519
Brian Ortiz,48.27,6.73,Male,No,Sat,Dinner,4,12.07,13.942407
Roger Taylor,24.71,5.85,Male,No,Thur,Lunch,2,12.36,23.674626
Shawn Blake,29.93,5.07,Male,No,Sun,Dinner,4,7.48,16.939526
Steven Carlson,34.30,6.70,Male,No,Thur,Lunch,6,5.72,19.533528
Gregory Clark,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,19.681165
Larry White,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,71.034483
Jason Cox,23.33,5.65,Male,Yes,Sun,Dinner,2,11.66,24.217745
Dr. Michael James,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,28.053517
Christopher Li,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,19.930475
Alex Williamson,48.33,9.00,Male,No,Sat,Dinner,4,12.08,18.621974
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,20.392697

In [190]:
df[df['day'].isin(['Sun' , 'Sat' , 'Thur'])]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
payer_name,,,,,,,,,
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,5.944673
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,16.054159
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,13.978041
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,14.680765
Erik Smith,25.29,4.71,Male,No,Sun,Dinner,4,6.32,18.623962
...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,20.392697
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.358352
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,8.822232
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,9.820426
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,15.974441

In [191]:
df[~(df['day'] == 'Sun')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,generousity
payer_name,,,,,,,,,
Timothy Oneal,20.65,3.35,Male,No,Sat,Dinner,3,6.88,16.222760
Thomas Rice,17.92,4.08,Male,No,Sat,Dinner,2,8.96,22.767857
Natalie Gardner,20.29,2.75,Female,No,Sat,Dinner,2,10.14,13.553475
Ashley Shelton,15.77,2.23,Female,No,Sat,Dinner,2,7.88,14.140774
Lance Peterson,39.42,7.58,Male,No,Sat,Dinner,4,9.86,19.228818
...,...,...,...,...,...,...,...,...,...
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,20.392697
Monica Sanders,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,7.358352
Keith Wong,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,8.822232
Dennis Dixon,17.82,1.75,Male,No,Sat,Dinner,2,8.91,9.820426
Michelle Hardin,18.78,3.00,Female,No,Thur,Dinner,2,9.39,15.974441

In [207]:
from numpy import random as rd

In [217]:
df = pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [218]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id'],
      dtype='object')

In [219]:
def funct(data):
    return str(data)[-4:]

In [220]:
# df['cc_number'] = df['cc_number'].apply(funct)

In [221]:
df[['cc_number']]

            cc_number
0    3560325168603410
1    4478071379779230
2    6011812112971322
3    4676137647685994
4    4832732618637221
..                ...
239  5296068606052842
240  3506806155565404
241  6011891618747196
242     4375220550950
243  3511451626698139

[244 rows x 1 columns]

In [223]:
# En hızlı yol : Vectorized
df['cc_number'] = df['cc_number'].astype(str).str[-4:]

In [224]:
# 10 dolardan az ödediyse $ 10-30 arası $$ 30'dan fazlaysa $$$ 
# işareti bulunan fiyat kategorisi eklea

In [225]:
Numpy_Array = np.array([[1, 2, 3], [4, 5, 6]])
filled_array = np.full_like(Numpy_Array, fill_value=7)
print("Numpy Array filled with 7 -\n", filled_array)

Numpy Array filled with 7 -
 [[7 7 7]
 [7 7 7]]

In [238]:
def order(data):
    rank = np.full_like(data , '$', dtype='U3')
    rank[(data >= 10) & (data<30)] = '$$'
    rank[(data >= 30)] = '$$$'
    return rank

In [ ]:
df['Payment Category'] = order(df['total_bill'].values)

In [252]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [253]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'payer_name', 'cc_number', 'payment_id',
       'payment_category'],
      dtype='object')

In [254]:
df[['payment_category']]

    payment_category
0                 $$
1                 $$
2                 $$
3                 $$
4                 $$
..               ...
239               $$
240               $$
241               $$
242               $$
243               $$

[244 rows x 1 columns]

In [255]:
np.square(df[['total_bill' , 'tip']])

     total_bill      tip
0      288.6601   1.0201
1      106.9156   2.7556
2      441.4201  12.2500
3      560.7424  10.9561
4      604.6681  13.0321
..          ...      ...
239    842.7409  35.0464
240    738.7524   4.0000
241    513.9289   4.0000
242    317.5524   3.0625
243    352.6884   9.0000

[244 rows x 2 columns]

In [259]:
df.sort_values(by= ['tip','total_bill' ] , ascending=False , inplace=True)
df.head(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,payment_id,payment_category
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,9808,Sat239,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,8508,Thur1025,$$$
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,1962,Sat3374,$$
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,9162,Sun6059,$$
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,4186,Sun9677,$$$
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,2842,Sat2657,$$
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,9955,Thur9003,$$

In [261]:
df.reset_index(inplace=True , drop = True)
# Eski sırayı drop ile sildik.
df.head(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,payer_name,cc_number,payment_id,payment_category
0,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,8236,Sat1954,$$$
1,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,5212,Sat4590,$$$
2,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,9808,Sat239,$$$
3,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,0595,Sat8139,$$$
4,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,8508,Thur1025,$$$
5,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,1962,Sat3374,$$
6,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,9162,Sun6059,$$
7,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,4186,Sun9677,$$$
8,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,2842,Sat2657,$$
9,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,9955,Thur9003,$$